inherit_from: "configs/rgbd/tum/fr3_office.yaml"

Results:
  eval_rendering: true

# A0: Baseline — FFT Edge VO on, FFT mask seeding on
FFTEdgeVO:
  use_fft_edge_vo: true

Ablation:
  use_loop_closure: false
  use_fft_mask: true
